package collector

// defaultMetricDefinitions is the source of truth for built-in AC field metadata.
var defaultMetricDefinitions = [...]MetricDefinition{
	{FieldID: 2, Name: "vertiv_ac_temperature_return_air_celsius", Help: "Return air temperature measurement"},
	{FieldID: 157, Name: "vertiv_ac_temperature_supply_air_1_celsius", Help: "Air supply temperature 1 measured value"},
	{FieldID: 263, Name: "vertiv_ac_temperature_supply_air_2_celsius", Help: "Air supply temperature 2 measured value"},
	{FieldID: 325, Name: "vertiv_ac_temperature_supply_air_mean_celsius", Help: "Mean temperature measurement of Supply Air"},
	{FieldID: 323, Name: "vertiv_ac_temperature_supply_air_setpoint_celsius", Help: "Supply Air temperature setting"},
	{FieldID: 9, Name: "vertiv_ac_temperature_airflow_celsius", Help: "Air temperature measurement"},
	{FieldID: 10, Name: "vertiv_ac_temperature_exhaust_celsius", Help: "Exhaust temperature measurement"},
	{FieldID: 324, Name: "vertiv_ac_temperature_inspiratory_celsius", Help: "Inspiratory temperature measurement"},
	{FieldID: 34, Name: "vertiv_ac_temperature_inspiratory_evaporation_celsius", Help: "Inspiratory evaporation temperature"},
	{FieldID: 35, Name: "vertiv_ac_temperature_exhaust_condensing_celsius", Help: "Exhaust condensing temperature"},
	{FieldID: 36, Name: "vertiv_ac_temperature_inspiratory_superheat_celsius", Help: "Inspiratory superheat"},
	{FieldID: 37, Name: "vertiv_ac_temperature_exhaust_superheat_celsius", Help: "Exhaust superheat"},
	{FieldID: 114, Name: "vertiv_ac_temperature_return_air_setpoint_celsius", Help: "Return air temperature setting"},
	{FieldID: 113, Name: "vertiv_ac_temperature_remote_setpoint_celsius", Help: "Remote temperature setting"},
	{FieldID: 141, Name: "vertiv_ac_temperature_airflow_alarm_value_celsius", Help: "Air temperature alarm value"},
	{FieldID: 142, Name: "vertiv_ac_temperature_low_alarm_value_celsius", Help: "Low temperature alarm value"},
	{FieldID: 143, Name: "vertiv_ac_temperature_return_air_alarm_value_celsius", Help: "Return air temperature alarm value"},
	{FieldID: 146, Name: "vertiv_ac_temperature_airflow_loss_alarm_celsius", Help: "Airflow loss temperature alarm value"},
	{FieldID: 111, Name: "vertiv_ac_temperature_dead_zone_celsius", Help: "Temperature dead zone"},
	{FieldID: 127, Name: "vertiv_ac_temperature_dehumid_stop_diff_celsius", Help: "Dehumidification stop temperature difference"},
	{FieldID: 183, Name: "vertiv_ac_temperature_eev_superheat_setpoint_celsius", Help: "EEV superheat setting"},
	{FieldID: 186, Name: "vertiv_ac_temperature_eev_close_superheat_celsius", Help: "The EEV valve closes the superheat"},
	{FieldID: 130, Name: "vertiv_ac_temperature_remote_1_celsius", Help: "Remote temperature 1 measurements"},
	{FieldID: 131, Name: "vertiv_ac_temperature_remote_2_celsius", Help: "Remote temperature 2 measurements"},
	{FieldID: 132, Name: "vertiv_ac_temperature_remote_3_celsius", Help: "Remote temperature 3 measurements"},
	{FieldID: 140, Name: "vertiv_ac_temperature_remote_avg_celsius", Help: "Remote average temperature"},
	{FieldID: 15, Name: "vertiv_ac_temperature_supply_air_1_correction_celsius", Help: "Air supply temperature 1 correction value"},
	{FieldID: 16, Name: "vertiv_ac_temperature_supply_air_2_correction_celsius", Help: "Air supply temperature 2 correction value"},
	{FieldID: 17, Name: "vertiv_ac_temperature_return_air_correction_celsius", Help: "Return air temperature correction value"},
	{FieldID: 18, Name: "vertiv_ac_temperature_airflow_correction_celsius", Help: "Airflow temperature correction value"},
	{FieldID: 19, Name: "vertiv_ac_temperature_exhaust_correction_celsius", Help: "Exhaust temperature correction value"},
	{FieldID: 20, Name: "vertiv_ac_temperature_inspiratory_correction_celsius", Help: "Inspiratory temperature correction value"},
	{FieldID: 3, Name: "vertiv_ac_humidity_return_air_percent", Help: "Return air humidity measurement"},
	{FieldID: 4, Name: "vertiv_ac_humidity_return_air_setpoint_percent", Help: "Humidity setting"},
	{FieldID: 65, Name: "vertiv_ac_humidity_ratio_percent", Help: "Humidity ratio"},
	{FieldID: 38, Name: "vertiv_ac_humidity_supply_air_theoretical_percent", Help: "Theoretical air supply humidity"},
	{FieldID: 39, Name: "vertiv_ac_humidity_supply_air_current_percent", Help: "Current air supply humidity"},
	{FieldID: 112, Name: "vertiv_ac_humidity_dead_zone_percent", Help: "Humidity dead zone"},
	{FieldID: 144, Name: "vertiv_ac_humidity_return_air_high_alarm_percent", Help: "Return wind high humidity alarm value"},
	{FieldID: 145, Name: "vertiv_ac_humidity_return_air_low_alarm_percent", Help: "Return air low warning value"},
	{FieldID: 21, Name: "vertiv_ac_humidity_return_air_correction_percent", Help: "Return air humidity correction value"},
	{FieldID: 326, Name: "vertiv_ac_pressure_exhaust_bar", Help: "Exhaust pressure measurement"},
	{FieldID: 14, Name: "vertiv_ac_pressure_inspiratory_bar", Help: "Inspiratory pressure measurement"},
	{FieldID: 22, Name: "vertiv_ac_pressure_exhaust_correction_bar", Help: "Exhaust pressure correction value"},
	{FieldID: 23, Name: "vertiv_ac_pressure_inspiratory_correction_bar", Help: "Inspiratory pressure correction value"},
	{FieldID: 184, Name: "vertiv_ac_pressure_eev_mop_limit_bar", Help: "EEV MOP pressure limit"},
	{FieldID: 204, Name: "vertiv_ac_pressure_fan_max_speed_low_point_bar", Help: "Fan maximum speed low pressure point"},
	{FieldID: 205, Name: "vertiv_ac_pressure_fan_speed_low_point_bar", Help: "Fan speed low point"},
	{FieldID: 206, Name: "vertiv_ac_pressure_fan_down_low_point_bar", Help: "Fan down the low pressure point"},
	{FieldID: 207, Name: "vertiv_ac_pressure_fan_min_speed_bar", Help: "Minimum speed of the fan"},
	{FieldID: 208, Name: "vertiv_ac_pressure_comp_min_output_bar", Help: "Compressor minimum output low pressure point"},
	{FieldID: 209, Name: "vertiv_ac_pressure_comp_capacity_reduce_bar", Help: "Compressor capacity reduces low pressure point"},
	{FieldID: 210, Name: "vertiv_ac_pressure_comp_capacity_increase_bar", Help: "Compressor capacity increases low pressure point"},
	{FieldID: 211, Name: "vertiv_ac_pressure_comp_max_output_bar", Help: "Compressor maximum output low pressure point"},
	{FieldID: 26, Name: "vertiv_ac_electrical_voltage_phase_a_volts", Help: "Phase A voltage"},
	{FieldID: 27, Name: "vertiv_ac_electrical_voltage_phase_b_volts", Help: "B phase voltage"},
	{FieldID: 28, Name: "vertiv_ac_electrical_voltage_phase_c_volts", Help: "C phase voltage"},
	{FieldID: 29, Name: "vertiv_ac_electrical_frequency_hz", Help: "Power frequency"},
	{FieldID: 223, Name: "vertiv_ac_electrical_overvoltage_alarm_percent", Help: "Power overrun alarm value"},
	{FieldID: 224, Name: "vertiv_ac_electrical_undervoltage_alarm_percent", Help: "Power undervoltage alarm value"},
	{FieldID: 115, Name: "vertiv_ac_compressor_capacity_actual_percent", Help: "Compressor capacity actual value"},
	{FieldID: 116, Name: "vertiv_ac_compressor_capacity_output_percent", Help: "Compressor capacity output value"},
	{FieldID: 30, Name: "vertiv_ac_compressor_min_runtime_minutes", Help: "Compressor shortest running time"},
	{FieldID: 31, Name: "vertiv_ac_compressor_min_downtime_minutes", Help: "Compressor shortest downtime"},
	{FieldID: 158, Name: "vertiv_ac_compressor_start_demand_percent", Help: "Compressor start demand"},
	{FieldID: 159, Name: "vertiv_ac_compressor_stop_demand_percent", Help: "Compressor stops demand"},
	{FieldID: 160, Name: "vertiv_ac_compressor_min_capacity_percent", Help: "Compressor minimum capacity"},
	{FieldID: 316, Name: "vertiv_ac_compressor_standard_capacity_percent", Help: "Compressor standard capacity"},
	{FieldID: 162, Name: "vertiv_ac_compressor_max_capacity_percent", Help: "Compressor maximum capacity"},
	{FieldID: 164, Name: "vertiv_ac_compressor_start_capacity_percent", Help: "Compressor start capacity"},
	{FieldID: 165, Name: "vertiv_ac_compressor_dehumid_capacity_increase_percent", Help: "Compressor dehumidification capacity increases"},
	{FieldID: 166, Name: "vertiv_ac_compressor_max_capacity_runtime_minutes", Help: "Maximum capacity of the compressor running time"},
	{FieldID: 167, Name: "vertiv_ac_compressor_start_time_seconds", Help: "Compressor start time"},
	{FieldID: 168, Name: "vertiv_ac_compressor_output_dead_zone_percent", Help: "Compressor output dead zone"},
	{FieldID: 169, Name: "vertiv_ac_compressor_oil_return_cycle_minutes", Help: "Oil return cycle"},
	{FieldID: 170, Name: "vertiv_ac_compressor_oil_return_runtime_minutes", Help: "Oil return running time"},
	{FieldID: 171, Name: "vertiv_ac_compressor_oil_return_capacity_percent", Help: "Oil return capacity"},
	{FieldID: 151, Name: "vertiv_ac_compressor_temp_proportional_band_celsius", Help: "Compressor temperature proportional band"},
	{FieldID: 152, Name: "vertiv_ac_compressor_temp_integration_time_seconds", Help: "Compressor temperature integration time"},
	{FieldID: 153, Name: "vertiv_ac_compressor_temp_differential_time_seconds", Help: "Compressor temperature differential time"},
	{FieldID: 48, Name: "vertiv_ac_compressor_running_hours_total", Help: "Compressor running hours"},
	{FieldID: 43, Name: "vertiv_ac_compressor_startstop_records_total", Help: "Number of compressor start and stop records"},
	{FieldID: 128, Name: "vertiv_ac_compressor_high_pressure_anomalies_total", Help: "Number of high pressure anomalies recorded"},
	{FieldID: 117, Name: "vertiv_ac_fan_speed_percent", Help: "Fan speed"},
	{FieldID: 172, Name: "vertiv_ac_fan_min_speed_percent", Help: "Fan minimum speed"},
	{FieldID: 173, Name: "vertiv_ac_fan_standard_speed_percent", Help: "Fan standard speed"},
	{FieldID: 176, Name: "vertiv_ac_fan_humidification_speed_percent", Help: "Fan humidification speed"},
	{FieldID: 177, Name: "vertiv_ac_fan_analog_output_lower_percent", Help: "Fan analog output lower limit"},
	{FieldID: 178, Name: "vertiv_ac_fan_analog_output_upper_percent", Help: "Fan analog output upper limit"},
	{FieldID: 179, Name: "vertiv_ac_fan_low_speed_step_percent_per_sec", Help: "Fan low speed step"},
	{FieldID: 180, Name: "vertiv_ac_fan_high_speed_step_percent_per_sec", Help: "Fan high speed step"},
	{FieldID: 181, Name: "vertiv_ac_fan_down_delay_seconds", Help: "Fan down delay"},
	{FieldID: 32, Name: "vertiv_ac_fan_start_delay_seconds", Help: "Fan start delay"},
	{FieldID: 33, Name: "vertiv_ac_fan_downtime_seconds", Help: "Fan downtime"},
	{FieldID: 154, Name: "vertiv_ac_fan_temp_proportional_band_celsius", Help: "Fan temperature proportional band"},
	{FieldID: 155, Name: "vertiv_ac_fan_temp_integration_time_seconds", Help: "Fan temperature integration time"},
	{FieldID: 50, Name: "vertiv_ac_fan_running_hours_total", Help: "Fan running hours"},
	{FieldID: 45, Name: "vertiv_ac_fan_startstop_records_total", Help: "Number of fan start and stop records"},
	{FieldID: 118, Name: "vertiv_ac_eev_opening_degree_percent", Help: "Expansion valve opening degree"},
	{FieldID: 182, Name: "vertiv_ac_eev_time_constant_seconds", Help: "EEV time constant"},
	{FieldID: 185, Name: "vertiv_ac_eev_start_opening_percent", Help: "EEV start opening degree"},
	{FieldID: 203, Name: "vertiv_ac_eev_start_time_seconds", Help: "EEV start time"},
	{FieldID: 49, Name: "vertiv_ac_pump_running_hours_total", Help: "Pump running hours"},
	{FieldID: 44, Name: "vertiv_ac_pump_startstop_records_total", Help: "Number of pump start and stop records"},
	{FieldID: 52, Name: "vertiv_ac_humidifier_running_hours_total", Help: "Humidifier running hours"},
	{FieldID: 47, Name: "vertiv_ac_humidifier_startstop_records_total", Help: "Number of humidifier start and stop records"},
	{FieldID: 51, Name: "vertiv_ac_electric_heating_running_hours_total", Help: "Electric heating operation hours"},
	{FieldID: 46, Name: "vertiv_ac_electric_heating_startstop_records_total", Help: "Number of electric heating start and stop records"},
	{FieldID: 126, Name: "vertiv_ac_dehumidification_runtime_minutes", Help: "Dehumidification run time"},
	{FieldID: 123, Name: "vertiv_ac_filter_maintenance_interval_days", Help: "Filter maintenance reminder time"},
	{FieldID: 5, Name: "vertiv_ac_status_operation", Help: "Air conditioning operation status"},
	{FieldID: 8, Name: "vertiv_ac_status_refrigeration", Help: "Refrigeration flag"},
	{FieldID: 11, Name: "vertiv_ac_status_heating", Help: "Heating flag"},
	{FieldID: 12, Name: "vertiv_ac_status_humidification", Help: "Humidification mark"},
	{FieldID: 13, Name: "vertiv_ac_status_dehumidification", Help: "Dehumidification mark"},
	{FieldID: 261, Name: "vertiv_ac_status_compressor_output", Help: "Compressor output"},
	{FieldID: 7, Name: "vertiv_ac_status_fan_output", Help: "Fan output"},
	{FieldID: 262, Name: "vertiv_ac_status_electric_heating_output", Help: "Electric heating output"},
	{FieldID: 264, Name: "vertiv_ac_status_humidifier_output", Help: "Humidifier output"},
	{FieldID: 260, Name: "vertiv_ac_status_condensate_pump_output", Help: "Condensate pump output"},
	{FieldID: 266, Name: "vertiv_ac_status_liquid_solenoid_valve_output", Help: "Liquid circuit solenoid valve output"},
	{FieldID: 265, Name: "vertiv_ac_status_public_alarm_output", Help: "Public alarm output"},
	{FieldID: 267, Name: "vertiv_ac_status_high_pressure_alarm", Help: "High pressure alarm"},
	{FieldID: 258, Name: "vertiv_ac_status_water_level_switch", Help: "Water level switch"},
	{FieldID: 259, Name: "vertiv_ac_status_remote_switch", Help: "Remote switch"},
	{FieldID: 161, Name: "vertiv_ac_status_fan_1", Help: "Fan 1 state"},
	{FieldID: 317, Name: "vertiv_ac_status_fan_2", Help: "Fan 2 state"},
	{FieldID: 318, Name: "vertiv_ac_status_fan_3", Help: "Fan 3 state"},
	{FieldID: 319, Name: "vertiv_ac_status_fan_4", Help: "Fan 4 state"},
	{FieldID: 311, Name: "vertiv_ac_status_new_alarm_flag", Help: "New alarm flag"},
	{FieldID: 315, Name: "vertiv_ac_status_filter_maintenance", Help: "Filter maintenance"},
	{FieldID: 91, Name: "vertiv_ac_status_communication", Help: "Communication Status"},
	{FieldID: 306, Name: "vertiv_ac_status_dehumidification_enabled", Help: "Dehumidification function enabled"},
	{FieldID: 305, Name: "vertiv_ac_status_humidification_enabled", Help: "Humidification function enabled"},
	{FieldID: 101, Name: "vertiv_ac_status_heating_function", Help: "Heating function"},
	{FieldID: 103, Name: "vertiv_ac_status_condensate_pump", Help: "Condensate pump"},
	{FieldID: 309, Name: "vertiv_ac_status_monitor_shutdown_enable", Help: "Monitor shutdown enable"},
	{FieldID: 310, Name: "vertiv_ac_status_soft_shutdown", Help: "Soft shutdown status"},
	{FieldID: 66, Name: "vertiv_ac_alarm_attr_high_voltage", Help: "High voltage alarm attribute"},
	{FieldID: 67, Name: "vertiv_ac_alarm_attr_low_voltage", Help: "Low voltage alarm attribute"},
	{FieldID: 69, Name: "vertiv_ac_alarm_attr_exhaust_high_temp", Help: "Exhaust high temperature alarm attribute"},
	{FieldID: 70, Name: "vertiv_ac_alarm_attr_exhaust_superheat_low", Help: "Exhaust superheat low alarm attribute"},
	{FieldID: 71, Name: "vertiv_ac_alarm_attr_return_air_temp", Help: "Return air temperature alarm attribute"},
	{FieldID: 72, Name: "vertiv_ac_alarm_attr_airflow_temp", Help: "Air temperature alarm attribute"},
	{FieldID: 74, Name: "vertiv_ac_alarm_attr_return_air_humidity", Help: "Return air humidity alarm attribute"},
	{FieldID: 75, Name: "vertiv_ac_alarm_attr_return_air_low_humidity", Help: "Return air low humidity alarm attribute"},
	{FieldID: 76, Name: "vertiv_ac_alarm_attr_high_voltage_lock", Help: "High voltage lock alarm attribute"},
	{FieldID: 77, Name: "vertiv_ac_alarm_attr_low_voltage_lock", Help: "Low-voltage lock alarm attribute"},
	{FieldID: 80, Name: "vertiv_ac_alarm_attr_power_loss", Help: "Power loss alarm attribute"},
	{FieldID: 81, Name: "vertiv_ac_alarm_attr_power_overvoltage", Help: "Power overvoltage alarm attribute"},
	{FieldID: 82, Name: "vertiv_ac_alarm_attr_power_undervoltage", Help: "Power undervoltage alarm attribute"},
	{FieldID: 84, Name: "vertiv_ac_alarm_attr_floor_overflow", Help: "Floor overflow alarm attribute"},
	{FieldID: 85, Name: "vertiv_ac_alarm_attr_high_water", Help: "High water alarm attribute"},
	{FieldID: 86, Name: "vertiv_ac_alarm_attr_filter_plugging", Help: "Filter plugging alarm attribute"},
	{FieldID: 88, Name: "vertiv_ac_alarm_attr_airflow_loss", Help: "Airflow loss alarm attribute"},
	{FieldID: 90, Name: "vertiv_ac_alarm_attr_remote_shutdown", Help: "Remote shutdown alarm attribute"},
	{FieldID: 93, Name: "vertiv_ac_alarm_attr_return_air_temp_sensor_fault", Help: "Return air temperature sensor fault alarm attribute"},
	{FieldID: 94, Name: "vertiv_ac_alarm_attr_return_air_humidity_sensor_fault", Help: "Return air humidity sensor fault alarm attribute"},
	{FieldID: 188, Name: "vertiv_ac_alarm_attr_exhaust_temp_sensor_fault", Help: "Exhaust temperature sensor fault alarm attribute"},
	{FieldID: 189, Name: "vertiv_ac_alarm_attr_fan_failure", Help: "Fan failure alarm attribute"},
	{FieldID: 190, Name: "vertiv_ac_alarm_attr_eev_comm_fault", Help: "EEV communication fault alarm attribute"},
	{FieldID: 192, Name: "vertiv_ac_alarm_attr_insufficient_refrigerant", Help: "Insufficient refrigerant alarm attribute"},
	{FieldID: 193, Name: "vertiv_ac_alarm_attr_inspiratory_temp_sensor_fault", Help: "Inhalation temperature sensor fault alarm attribute"},
	{FieldID: 195, Name: "vertiv_ac_alarm_attr_compressor_drive_comm_fault", Help: "Compressor Drive Communication Fault Alarm Attribute"},
	{FieldID: 196, Name: "vertiv_ac_alarm_attr_compressor_drive_failure", Help: "Compressor drive failure failure alarm"},
	{FieldID: 197, Name: "vertiv_ac_alarm_attr_compressor_radiator_over_temp", Help: "Compressor radiator over temperature alarm"},
	{FieldID: 198, Name: "vertiv_ac_alarm_attr_compressor_overcurrent", Help: "Compressor overcurrent alarm"},
	{FieldID: 199, Name: "vertiv_ac_alarm_attr_compressor_phase_failure", Help: "Compressor phase failure protection alarm"},
	{FieldID: 200, Name: "vertiv_ac_alarm_attr_busbar_voltage_exception", Help: "Busbar voltage exception alarm"},
	{FieldID: 201, Name: "vertiv_ac_alarm_attr_humidifier_fault", Help: "Humidifier fault alarm attribute"},
	{FieldID: 41, Name: "vertiv_ac_system_alarm_active_count", Help: "Number of alarm states"},
	{FieldID: 42, Name: "vertiv_ac_system_alarm_history_count", Help: "Number of alarm history"},
	{FieldID: 55, Name: "vertiv_ac_system_software_version_high", Help: "Software version is high"},
	{FieldID: 56, Name: "vertiv_ac_system_software_version_low", Help: "The software version is low"},
	{FieldID: 24, Name: "vertiv_ac_system_monitor_baud_rate", Help: "Monitor baud rate"},
	{FieldID: 25, Name: "vertiv_ac_system_monitor_address", Help: "Monitor the address"},
	{FieldID: 106, Name: "vertiv_ac_system_unit_count", Help: "Number of units"},
	{FieldID: 99, Name: "vertiv_ac_system_main_delay_minutes", Help: "Main delay"},
	{FieldID: 121, Name: "vertiv_ac_system_low_pressure_alarm_delay_seconds", Help: "Low pressure alarm delay"},
	{FieldID: 122, Name: "vertiv_ac_system_short_cycle_alarm_times_per_hour", Help: "Short cycle alarm value"},
	{FieldID: 124, Name: "vertiv_ac_system_exhaust_superheat_low_alarm_delay_sec", Help: "Exhaust superheat low alarm delay"},
}

func loadDefaultMetricDefinitions() map[int]MetricDefinition {
	definitions := make(map[int]MetricDefinition, len(defaultMetricDefinitions))
	for _, definition := range defaultMetricDefinitions {
		definitions[definition.FieldID] = definition
	}
	return definitions
}
