apiVersion: v2
name: vertiv-exporter
description: Prometheus exporter for Vertiv devices
type: application
version: 0.1.1
appVersion: "1.0.2"
home: https://github.com/airsmon/vertiv_exporter
sources:
  - https://github.com/airsmon/vertiv_exporter
keywords:
  - monitoring
  - prometheus
  - exporter
  - vertiv
maintainers:
  - name: airsmon
    url: https://github.com/airsmon
